Regards tool class and tool level for block destory actions
AlmuraDev/Almura pull request #516
Opened 2018-08-31 21:11 UTC by liach

Also ensured that every time of check an item stack instead of an item is passed.
Item stacks often carry crucial NBT data utilized by mods, especially IC2 (e.g. Mining drill)

Adds definition of tools. Next time instead of defining what tools work, just define the classes and level needed.
(e.g. instead of iron pickaxe, use tool class "pickaxe" and level 2 instead)

Resolves #515

Signed-off-by: liach <liach@users.noreply.github.com>

2018-09-06 22:39 UTC, liach commented
@kashike Can you review this?

2018-09-06 22:45 UTC, kashike requested changes

2018-09-06 22:45 UTC, kashike commented on src/main/java/com/almuradev/content/type/action/type/blockdestroy/processor/BlockDestroyActionContentProcessor.java
> +        with.addAll(tool(config.getNode(BlockDestroyActionConfig.TOOL)));
`this.`

2018-09-06 22:45 UTC, kashike commented on src/main/java/com/almuradev/content/type/item/definition/ItemAcceptable.java
> +        return test(new ItemStack((Item) item));
`this.`

2018-09-06 22:45 UTC, kashike commented on src/main/java/com/almuradev/content/type/item/definition/ItemAcceptable.java
> +    default boolean test(ItemType item) {
`final ItemType item`

2018-09-06 22:45 UTC, kashike commented on src/main/java/com/almuradev/content/type/item/definition/ToolDefinitionConfig.java
> +    String TOOL_CLASS = "tool_class";
`tool_type` preferred

2018-09-19 05:35 UTC, liach commented
@kashike See AlmuraDev/ServerContent#7. With this tool class system, even when a tool class does not exist, the game will not crash. And the original five lines of pickaxes can be replaced by one line of pickaxe tool class.

2018-09-20 01:56 UTC, liach commented
I am urging for another review. Even though kashike may be busy working on MCP, this patch allows modded tools to work on almura blocks properly with regard to the status of tools, and also can drastically decrease the size of effective tool check parts in the definition jsons.

2018-09-20 02:04 UTC, kashike approved these changes

2018-09-20 02:04 UTC, merged